# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIQGen', '0004_problem_measuredheight'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='autogenerated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
